import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// These are some fonts we get from Google to make the text look nice
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// This gives information to the browser, like the title on the top tab
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout is the main wrapper around all the pages in our app
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // We add our fonts here to style the whole app
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 'children' is the actual page content that gets put inside here */}
        {children}
      </body>
    </html>
  );
}
